### ISSUE TITLE
Cannot log in to server via ssh or see logs

### ISSUE THREAD

**Issue by atalyaalon** [data-for-change/dfc-iac#5]
I followed README instructions but didn't manage to perform basic commands:

```
➜  dfc-iac git:(main) bin/apps.py ssh
Traceback (most recent call last):
  File "bin/apps.py", line 204, in <module>
    main(*sys.argv[1:])
  File "bin/apps.py", line 196, in main
    res = globals()[cmd](*args)
  File "bin/apps.py", line 46, in ssh
    hostname = ssh_init()
  File "bin/apps.py", line 30, in ssh_init
    data = get_vault_kv_path('projects/iac/docker-server')
  File "bin/apps.py", line 24, in get_vault_kv_path
    'VAULT_TOKEN': VAULT_TOKEN,
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 488, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'vault': 'vault'
```

**Comment by atalyaalon** [comment]
my bad, didnt' installl vault, checking
